services:
  async-http-connector-proxy:
    build:
      context: async-http-connector-proxy
      dockerfile: dev.Dockerfile
    user: "${RUN_AS}"
    environment:
      HOME: "/app"
    env_file:
      - path: .env
        required: false
    ports:
      - 8200:8200/tcp
    volumes:
      - ./async-http-connector-proxy:/app
