chat:
  auto_reply: true
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  path_filters:
    - "!spiffworkflow-backend/migrations/**"
  auto_review:
    enabled: true
