
services:
  spiff-arena:
    build:
      context: .
      dockerfile: dev.Dockerfile
    user: "${RUN_AS}"
    environment:
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      XDG_CACHE_HOME: "/app/.cache"
    volumes:
      - ./:/app
