
services:
  spiff-arena:
    build:
      context: .
      dockerfile: dev.Dockerfile
    user: "${RUN_AS}"
    environment:
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      PRE_COMMIT_HOME: "/app/.cache/pre-commit"
    volumes:
      - ./:/app
