"""Process_instance."""
from __future__ import annotations


from spiffworkflow_backend.models.db import db
from spiffworkflow_backend.models.db import SpiffworkflowBaseDBModel


# the last three here should maybe become columns on process instance someday
# runtime_json
#   "bpmn_messages",
#   "correlations",
#   "data",
#   "subprocesses",
#   "tasks",
#   "last_task", # guid generated by spiff
#   "root", # guid generated by spiff
#   "success", # boolean
class ProcessInstanceDataModel(SpiffworkflowBaseDBModel):

    __tablename__ = "process_instance_data"
    id: int = db.Column(db.Integer, primary_key=True)
    # this is not deferred because there is no reason to query this model if you do not want the runtime_json
    runtime_json: str = db.Column(db.JSON, nullable=False)
