"""Process_instance."""
from __future__ import annotations
from sqlalchemy import ForeignKey
from spiffworkflow_backend.models.process_instance import ProcessInstanceModel

from sqlalchemy.orm import deferred

from spiffworkflow_backend.models.db import db
from spiffworkflow_backend.models.db import SpiffworkflowBaseDBModel


# the last three here should maybe become columns on process instance someday
# runtime_json
#   "bpmn_messages",
#   "correlations",
#   "data",
#   "subprocesses",
#   "tasks",
#   "last_task", # guid generated by spiff
#   "root", # guid generated by spiff
#   "success", # boolean
class ProcessInstanceDataModel(SpiffworkflowBaseDBModel):

    __tablename__ = "process_instance_data"
    id: int = db.Column(db.Integer, primary_key=True)
    process_instance_id: int = db.Column(
        ForeignKey(ProcessInstanceModel.id), nullable=False  # type: ignore
    )
    runtime_json: str | None = deferred(db.Column(db.JSON))  # type: ignore
