"""empty message

Revision ID: 07ab2dd9c3ad
Revises: ac125644907a
Create Date: 2024-07-17 10:17:00.156755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ab2dd9c3ad'
down_revision = 'ac125644907a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_schema',
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('version_control_revision', sa.String(length=255), nullable=False),
    sa.Column('process_model_identifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('hash', 'version_control_revision', 'process_model_identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_schema')
    # ### end Alembic commands ###
