"""empty message

Revision ID: 0b90171055cd
Revises: 4efc3d8655be
Create Date: 2026-01-04 10:38:41.603376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b90171055cd'
down_revision = '4efc3d8655be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_task_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_task_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['human_task_id'], ['human_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_task_id', 'group_id', name='human_task_group_unique')
    )
    with op.batch_alter_table('human_task_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_task_group_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_task_group_human_task_id'), ['human_task_id'], unique=False)

    op.create_table('human_task_user_waiting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_task_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['human_task_id'], ['human_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_task_id', 'username', name='human_task_user_waiting_unique')
    )
    with op.batch_alter_table('human_task_user_waiting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_task_user_waiting_human_task_id'), ['human_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_task_user_waiting_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task_user_waiting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_task_user_waiting_username'))
        batch_op.drop_index(batch_op.f('ix_human_task_user_waiting_human_task_id'))

    op.drop_table('human_task_user_waiting')
    with op.batch_alter_table('human_task_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_task_group_human_task_id'))
        batch_op.drop_index(batch_op.f('ix_human_task_group_group_id'))

    op.drop_table('human_task_group')
    # ### end Alembic commands ###
