"""increase_refresh_token_size

Revision ID: 0ee3c2c7faf7
Revises: cf591db15cec
Create Date: 2025-09-22 00:03:01.612841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee3c2c7faf7'
down_revision = 'cf591db15cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=4096),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###
