"""empty message

Revision ID: 0efe01a8fead
Revises: ffef09e6ddf1
Create Date: 2024-07-02 15:00:20.533240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efe01a8fead'
down_revision = 'ffef09e6ddf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance_event', schema=None) as batch_op:
        batch_op.create_foreign_key('process_instance_event_task_guid_fk', 'task', ['task_guid'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance_event', schema=None) as batch_op:
        batch_op.drop_constraint('process_instance_event_task_guid_fk', type_='foreignkey')

    # ### end Alembic commands ###
