"""empty message

Revision ID: 214e0c5fb418
Revises: 64adf34a98db
Create Date: 2023-07-11 14:52:15.825136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214e0c5fb418'
down_revision = '64adf34a98db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_instance_correlation_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correlation_key_names', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_instance_correlation_rule', schema=None) as batch_op:
        batch_op.drop_column('correlation_key_names')

    # ### end Alembic commands ###
