"""empty message

Revision ID: 27697f30eaf9
Revises: 214e0c5fb418
Create Date: 2023-08-17 13:47:36.964088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27697f30eaf9'
down_revision = '214e0c5fb418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('allow_anonymous')

    # ### end Alembic commands ###
