"""empty message

Revision ID: 28269dabeb4b
Revises: 214e0c5fb418
Create Date: 2023-08-18 08:14:28.964221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28269dabeb4b'
down_revision = '214e0c5fb418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_guest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('allow_guest')

    # ### end Alembic commands ###
