"""empty message

Revision ID: 2d68edd689b9
Revises: d9d54e36c69f
Create Date: 2026-08-21 10:05:15.093498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d68edd689b9'
down_revision = 'd9d54e36c69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bpmn_process_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bpmn_process_definition_single_process_hash'), ['single_process_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bpmn_process_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bpmn_process_definition_single_process_hash'))

    # ### end Alembic commands ###
