"""empty message

Revision ID: 2fe2830f45e1
Revises: 317dd5155137
Create Date: 2023-03-02 17:19:08.535027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe2830f45e1'
down_revision = '317dd5155137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('json_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_json_data_hash'), 'json_data', ['hash'], unique=True)
    op.create_table('bpmn_process_definition_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bpmn_process_definition_parent_id', sa.Integer(), nullable=False),
    sa.Column('bpmn_process_definition_child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bpmn_process_definition_child_id'], ['bpmn_process_definition.id'], ),
    sa.ForeignKeyConstraint(['bpmn_process_definition_parent_id'], ['bpmn_process_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bpmn_process_definition_relationship')
    op.drop_index(op.f('ix_json_data_hash'), table_name='json_data')
    op.drop_table('json_data')
    # ### end Alembic commands ###
