"""empty message

Revision ID: 3004c4a0e617
Revises: 844cee572018
Create Date: 2023-09-12 14:48:52.189482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3004c4a0e617'
down_revision = '844cee572018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=36), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by_user_id', name='service_account_uniq')
    )
    with op.batch_alter_table('service_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_account_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_account_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_account_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_account_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_account_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_account_name'))
        batch_op.drop_index(batch_op.f('ix_service_account_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_account_api_key'))

    op.drop_table('service_account')
    # ### end Alembic commands ###
