"""empty message

Revision ID: 349b48184dfe
Revises: 1073364bc015
Create Date: 2023-09-06 15:12:46.048678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349b48184dfe'
down_revision = '1073364bc015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='user_id_key_uniq')
    )
    with op.batch_alter_table('user_property', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_property_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_property_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_property_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_property_key'))

    op.drop_table('user_property')
    # ### end Alembic commands ###
