"""empty message

Revision ID: 36241ec6747b
Revises: 44a8f46cc508
Create Date: 2023-04-19 10:31:23.202482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36241ec6747b'
down_revision = '44a8f46cc508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_caller_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_identifier', sa.String(length=255), nullable=True),
    sa.Column('calling_process_identifier', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_caller_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_caller_cache_process_identifier'), ['process_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_caller_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_caller_cache_process_identifier'))

    op.drop_table('process_caller_cache')
    # ### end Alembic commands ###
