"""empty message

Revision ID: 3f4639691223
Revises: d8901960326e
Create Date: 2023-11-07 16:42:28.529028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f4639691223'
down_revision = 'd8901960326e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correlation_property_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_correlation_property_cache_message_name')
        batch_op.drop_index('ix_correlation_property_cache_name')

    op.drop_table('correlation_property_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_property_cache',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50), nullable=False),
    sa.Column('message_name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50), nullable=False),
    sa.Column('process_model_id', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255), nullable=False),
    sa.Column('retrieval_expression', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('correlation_property_cache', schema=None) as batch_op:
        batch_op.create_index('ix_correlation_property_cache_name', ['name'], unique=False)
        batch_op.create_index('ix_correlation_property_cache_message_name', ['message_name'], unique=False)

    # ### end Alembic commands ###
