"""empty message

Revision ID: 4efc3d8655be
Revises: e102044e51f8
Create Date: 2025-12-03 10:30:02.738210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efc3d8655be'
down_revision = 'e102044e51f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('process_instance_id', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_log_duration_ms'), ['duration_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_log_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_log_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_log_process_instance_id'), ['process_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_log_status_code'), ['status_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_log_status_code'))
        batch_op.drop_index(batch_op.f('ix_api_log_process_instance_id'))
        batch_op.drop_index(batch_op.f('ix_api_log_method'))
        batch_op.drop_index(batch_op.f('ix_api_log_endpoint'))
        batch_op.drop_index(batch_op.f('ix_api_log_duration_ms'))
        batch_op.drop_index(batch_op.f('ix_api_log_created_at'))

    op.drop_table('api_log')
    # ### end Alembic commands ###
