"""empty message

Revision ID: 553ba18e4076
Revises: e494a3955ce5
Create Date: 2023-03-01 11:31:20.619328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '553ba18e4076'
down_revision = 'e494a3955ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_instance', sa.Column('process_instance_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'process_instance', 'process_instance_data', ['process_instance_data_id'], ['id'])
    op.alter_column('process_instance_data', 'runtime_json',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_constraint('process_instance_data_ibfk_1', 'process_instance_data', type_='foreignkey')
    op.drop_column('process_instance_data', 'process_instance_id')
    op.alter_column('serialized_bpmn_definition', 'static_json',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_index('ix_serialized_bpmn_definition_hash', table_name='serialized_bpmn_definition')
    op.create_index(op.f('ix_serialized_bpmn_definition_hash'), 'serialized_bpmn_definition', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serialized_bpmn_definition_hash'), table_name='serialized_bpmn_definition')
    op.create_index('ix_serialized_bpmn_definition_hash', 'serialized_bpmn_definition', ['hash'], unique=False)
    op.alter_column('serialized_bpmn_definition', 'static_json',
               existing_type=mysql.JSON(),
               nullable=True)
    op.add_column('process_instance_data', sa.Column('process_instance_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('process_instance_data_ibfk_1', 'process_instance_data', 'process_instance', ['process_instance_id'], ['id'])
    op.alter_column('process_instance_data', 'runtime_json',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_constraint(None, 'process_instance', type_='foreignkey')
    op.drop_column('process_instance', 'process_instance_data_id')
    # ### end Alembic commands ###
