"""empty message

Revision ID: 5579975401dd
Revises: 1073364bc015
Create Date: 2023-09-01 11:07:39.816184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5579975401dd'
down_revision = '1073364bc015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime_info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('runtime_info')

    # ### end Alembic commands ###
