"""empty message

Revision ID: 567d22ded3af
Revises: 2fe2830f45e1
Create Date: 2023-03-03 08:38:25.855923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567d22ded3af'
down_revision = '2fe2830f45e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bpmn_process_definition_relationship_unique', 'bpmn_process_definition_relationship', ['bpmn_process_definition_parent_id', 'bpmn_process_definition_child_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bpmn_process_definition_relationship_unique', 'bpmn_process_definition_relationship', type_='unique')
    # ### end Alembic commands ###
