"""empty message

Revision ID: 5bb19de48185
Revises: 441dca328887
Create Date: 2023-12-18 10:17:18.516211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb19de48185'
down_revision = '441dca328887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('json_data_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('json_data_store', schema=None) as batch_op:
        batch_op.drop_column('schema')

    # ### end Alembic commands ###
