"""empty message

Revision ID: 5c50ecf2c1cd
Revises: 64adf34a98db
Create Date: 2023-08-08 11:21:15.278625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c50ecf2c1cd'
down_revision = '64adf34a98db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_category'))

    op.drop_table('configuration')
    # ### end Alembic commands ###
