"""empty message

Revision ID: 5d07e3db3ab7
Revises: b036313a7ee0
Create Date: 2023-11-22 13:58:21.228702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d07e3db3ab7'
down_revision = 'b036313a7ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.alter_column('instruction',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.alter_column('instruction',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
