"""empty message

Revision ID: 61cd3e8462f5
Revises: 941f7b76d278
Create Date: 2023-03-03 16:22:12.449757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61cd3e8462f5'
down_revision = '941f7b76d278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_ibfk_2', 'task', type_='foreignkey')
    op.drop_column('task', 'task_definition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_definition_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_ibfk_2', 'task', 'task_definition', ['task_definition_id'], ['id'])
    # ### end Alembic commands ###
