"""empty message

Revision ID: 6315ff2525b0
Revises: 567d22ded3af
Create Date: 2023-03-03 09:19:28.098057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6315ff2525b0'
down_revision = '567d22ded3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_instance', sa.Column('bpmn_process_definition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'process_instance', 'bpmn_process_definition', ['bpmn_process_definition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_instance', type_='foreignkey')
    op.drop_column('process_instance', 'bpmn_process_definition_id')
    # ### end Alembic commands ###
