"""empty message

Revision ID: 664bb2f00694
Revises: 0c7428378d6e
Create Date: 2023-04-27 13:32:04.143969

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '664bb2f00694'
down_revision = '0c7428378d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_updated_at_in_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.drop_column('task_updated_at_in_seconds')

    # ### end Alembic commands ###
