"""empty message

Revision ID: 698a921acb46
Revises: 4d438975ff4d
Create Date: 2023-09-27 11:15:33.302047

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '698a921acb46'
down_revision = '4d438975ff4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_triggerable_process_model', schema=None) as batch_op:
        batch_op.alter_column('process_model_identifier',
               existing_type=sa.String(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_triggerable_process_model', schema=None) as batch_op:
        batch_op.alter_column('process_model_identifier',
               existing_type=sa.String(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
