"""empty message

Revision ID: 7422be14adc4
Revises: ac6b60d7fee9
Create Date: 2023-03-01 15:39:25.731722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7422be14adc4'
down_revision = 'ac6b60d7fee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_instance_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serialized_bpmn_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('static_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serialized_bpmn_definition_hash'), 'serialized_bpmn_definition', ['hash'], unique=True)
    op.add_column('process_instance', sa.Column('serialized_bpmn_definition_id', sa.Integer(), nullable=True))
    op.add_column('process_instance', sa.Column('process_instance_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'process_instance', 'process_instance_data', ['process_instance_data_id'], ['id'])
    op.create_foreign_key(None, 'process_instance', 'serialized_bpmn_definition', ['serialized_bpmn_definition_id'], ['id'])
    op.add_column('spiff_step_details', sa.Column('delta_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spiff_step_details', 'delta_json')
    op.drop_constraint('process_instance_ibfk_3', 'process_instance', type_='foreignkey')
    op.drop_constraint('process_instance_ibfk_2', 'process_instance', type_='foreignkey')
    op.drop_column('process_instance', 'process_instance_data_id')
    op.drop_column('process_instance', 'serialized_bpmn_definition_id')
    op.drop_index(op.f('ix_serialized_bpmn_definition_hash'), table_name='serialized_bpmn_definition')
    op.drop_table('serialized_bpmn_definition')
    op.drop_table('process_instance_data')
    # ### end Alembic commands ###
