"""empty message

Revision ID: 7aafbb3fcad6
Revises: 881cdb50a567
Create Date: 2023-06-27 13:45:21.121427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aafbb3fcad6'
down_revision = '881cdb50a567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_draft_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=False),
    sa.Column('task_definition_id_path', sa.String(length=255), nullable=False),
    sa.Column('saved_form_data_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_instance_id', 'task_definition_id_path', name='process_instance_task_definition_unique')
    )
    with op.batch_alter_table('task_draft_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_draft_data_process_instance_id'), ['process_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_draft_data_saved_form_data_hash'), ['saved_form_data_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_draft_data_task_definition_id_path'), ['task_definition_id_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_draft_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_draft_data_task_definition_id_path'))
        batch_op.drop_index(batch_op.f('ix_task_draft_data_saved_form_data_hash'))
        batch_op.drop_index(batch_op.f('ix_task_draft_data_process_instance_id'))

    op.drop_table('task_draft_data')
    # ### end Alembic commands ###
