"""empty message

Revision ID: 7eaec0e12079
Revises: 43afc70a7016
Create Date: 2024-06-18 16:45:06.102210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eaec0e12079'
down_revision = '43afc70a7016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.create_foreign_key('future_task_task_guid_fk', 'task', ['guid'], ['guid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.drop_constraint('future_task_task_guid_fk', type_='foreignkey')

    # ### end Alembic commands ###
