"""empty message

Revision ID: 881cdb50a567
Revises: 377be1608b45
Create Date: 2023-06-20 15:26:28.087551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881cdb50a567'
down_revision = '377be1608b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_form_data_hash', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_saved_form_data_hash'), ['saved_form_data_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_saved_form_data_hash'))
        batch_op.drop_column('saved_form_data_hash')

    # ### end Alembic commands ###
