"""empty message

Revision ID: 8b258f77eafe
Revises: 4efc3d8655be
Create Date: 2026-01-12 16:59:26.261161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b258f77eafe'
down_revision = '4efc3d8655be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_draft_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_guid', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_task_draft_data_task_definition_id_path'))
        batch_op.drop_index(batch_op.f('process_instance_task_definition_unique'))
        batch_op.create_index(batch_op.f('ix_task_draft_data_task_guid'), ['task_guid'], unique=False)
        batch_op.create_unique_constraint('process_instance_task_unique', ['process_instance_id', 'task_guid'])
        batch_op.create_foreign_key(None, 'task', ['task_guid'], ['guid'])
        batch_op.drop_column('task_definition_id_path')

    # TODO: this should get all tasks with task_definition_id_path=whatever and then set the hash
    # to the same json model hash.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_draft_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_definition_id_path', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('process_instance_task_unique', type_='unique')
        batch_op.drop_index(batch_op.f('ix_task_draft_data_task_guid'))
        batch_op.create_index(batch_op.f('process_instance_task_definition_unique'), ['process_instance_id', 'task_definition_id_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_task_draft_data_task_definition_id_path'), ['task_definition_id_path'], unique=False)
        batch_op.drop_column('task_guid')

    # ### end Alembic commands ###
