"""empty message

Revision ID: 8db020e15f26
Revises: ef3fc0930156
Create Date: 2023-11-29 14:21:32.796690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8db020e15f26'
down_revision = 'ef3fc0930156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))
        batch_op.drop_index('ix_future_task_status')
        batch_op.create_index(batch_op.f('ix_future_task_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_future_task_run_at_in_seconds'), ['run_at_in_seconds'], unique=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_future_task_run_at_in_seconds'))
        batch_op.drop_index(batch_op.f('ix_future_task_completed'))
        batch_op.create_index('ix_future_task_status', ['status'], unique=False)
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
