"""empty message

Revision ID: 941f7b76d278
Revises: b0b82fab4cf9
Create Date: 2023-03-03 14:40:46.574985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941f7b76d278'
down_revision = 'b0b82fab4cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bpmn_process', sa.Column('guid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bpmn_process_guid'), 'bpmn_process', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bpmn_process_guid'), table_name='bpmn_process')
    op.drop_column('bpmn_process', 'guid')
    # ### end Alembic commands ###
