"""empty message

Revision ID: a6f39b4dd3b8
Revises: d8901960326e
Create Date: 2023-11-17 16:19:44.874639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f39b4dd3b8'
down_revision = 'd8901960326e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_task',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('run_at_in_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_future_task_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_future_task_status'))

    op.drop_table('future_task')
    # ### end Alembic commands ###
