"""empty message

Revision ID: ac125644907a
Revises: ffef09e6ddf1
Create Date: 2024-07-09 15:47:15.355999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac125644907a'
down_revision = 'ffef09e6ddf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_instance_migration_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_instance_event_id', sa.Integer(), nullable=False),
    sa.Column('initial_git_revision', sa.String(length=64), nullable=True),
    sa.Column('target_git_revision', sa.String(length=64), nullable=True),
    sa.Column('initial_bpmn_process_hash', sa.String(length=64), nullable=False),
    sa.Column('target_bpmn_process_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['process_instance_event_id'], ['process_instance_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_instance_migration_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_instance_migration_detail_process_instance_event_id'), ['process_instance_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance_migration_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_instance_migration_detail_process_instance_event_id'))

    op.drop_table('process_instance_migration_detail')
    # ### end Alembic commands ###
