"""empty message

Revision ID: ada8eab55f1a
Revises: d4b900e71852
Create Date: 2024-05-17 14:10:40.077081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada8eab55f1a'
down_revision = 'd4b900e71852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compressed_data',
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('compressed_data', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('hash'),
    sa.UniqueConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compressed_data')
    # ### end Alembic commands ###
