"""empty message

Revision ID: b036313a7ee0
Revises: d8901960326e
Create Date: 2023-11-21 15:12:33.971161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b036313a7ee0'
down_revision = 'd8901960326e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_task',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('run_at_in_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_future_task_status'), ['status'], unique=False)

    op.create_table('task_instructions_for_end_user',
    sa.Column('task_guid', sa.String(length=36), nullable=False),
    sa.Column('instruction', sa.String(length=255), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DECIMAL(precision=17, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.PrimaryKeyConstraint('task_guid')
    )
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_instructions_for_end_user_process_instance_id'), ['process_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_instructions_for_end_user_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_instructions_for_end_user_timestamp'))
        batch_op.drop_index(batch_op.f('ix_task_instructions_for_end_user_process_instance_id'))

    op.drop_table('task_instructions_for_end_user')
    with op.batch_alter_table('future_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_future_task_status'))

    op.drop_table('future_task')
    # ### end Alembic commands ###
