"""empty message

Revision ID: b0b82fab4cf9
Revises: a63a61a21398
Create Date: 2023-03-03 13:24:08.304492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b82fab4cf9'
down_revision = 'a63a61a21398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_instance', sa.Column('bpmn_process_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'process_instance', 'bpmn_process', ['bpmn_process_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_instance', type_='foreignkey')
    op.drop_column('process_instance', 'bpmn_process_id')
    # ### end Alembic commands ###
