"""empty message

Revision ID: b91143f4e414
Revises: 63fc8d693b9f
Create Date: 2023-02-25 22:46:03.533624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91143f4e414'
down_revision = '63fc8d693b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_task', sa.Column('process_model_identifier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human_task', 'process_model_identifier')
    # ### end Alembic commands ###
