"""empty message

Revision ID: b9a7cf115630
Revises: f318f9f1b110
Create Date: 2024-08-12 15:17:40.990772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9a7cf115630'
down_revision = 'f318f9f1b110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.alter_column('task_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('human_task_user', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task_user', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               existing_nullable=True)

    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.alter_column('task_title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
