"""empty message

Revision ID: bbc242f01974
Revises: efa7a9f771a6
Create Date: 2025-11-19 15:12:38.982148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc242f01974'
down_revision = 'efa7a9f771a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pkce_code_verifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pkce_id', sa.String(length=512), nullable=False),
    sa.Column('code_verifier', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pkce_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pkce_code_verifier')
    # ### end Alembic commands ###
