"""empty message

Revision ID: c07fbe70cb58
Revises: c6e246c3c04e
Create Date: 2024-03-27 17:39:45.246725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c07fbe70cb58"
down_revision = "d4b900e71852"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("schema", sa.JSON(), nullable=False),
        sa.Column("updated_at_in_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at_in_seconds", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier", "location", name="_message_identifier_location_unique"),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_message_identifier"), ["identifier"], unique=False)

    op.create_table(
        "message_correlation_property",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("retrieval_expression", sa.String(length=255), nullable=False),
        sa.Column("updated_at_in_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at_in_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "identifier", name="_message_correlation_property_unique"),
    )
    with op.batch_alter_table("message_correlation_property", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_message_correlation_property_identifier"), ["identifier"], unique=False)
        batch_op.create_index(batch_op.f("ix_message_correlation_property_message_id"), ["message_id"], unique=False)

    with op.batch_alter_table("correlation_property_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_correlation_property_cache_message_name")
        batch_op.drop_index("ix_correlation_property_cache_name")

    op.drop_table("correlation_property_cache")
    # with op.batch_alter_table("task", schema=None) as batch_op:
    #     batch_op.drop_constraint("guid", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_unique_constraint("guid", ["guid"])

    op.create_table(
        "correlation_property_cache",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("message_name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("process_model_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("retrieval_expression", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("correlation_property_cache", schema=None) as batch_op:
        batch_op.create_index("ix_correlation_property_cache_name", ["name"], unique=False)
        batch_op.create_index("ix_correlation_property_cache_message_name", ["message_name"], unique=False)

    with op.batch_alter_table("message_correlation_property", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_correlation_property_message_id"))
        batch_op.drop_index(batch_op.f("ix_message_correlation_property_identifier"))

    op.drop_table("message_correlation_property")
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_identifier"))

    op.drop_table("message")
    # ### end Alembic commands ###
