"""empty message

Revision ID: c3abd6eefbff
Revises: b9a7cf115630
Create Date: 2025-07-23 16:23:49.755804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3abd6eefbff'
down_revision = 'b9a7cf115630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_instance_last_milestone_bpmn_name'), ['last_milestone_bpmn_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_instance_last_milestone_bpmn_name'))

    # ### end Alembic commands ###
