"""empty message

Revision ID: ca9b79dde5cc
Revises: 2ec4222f0012
Create Date: 2023-02-03 21:06:56.396816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9b79dde5cc'
down_revision = '2ec4222f0012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tenant_specific_field_1', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('tenant_specific_field_2', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('tenant_specific_field_3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tenant_specific_field_3')
    op.drop_column('user', 'tenant_specific_field_2')
    op.drop_column('user', 'tenant_specific_field_1')
    # ### end Alembic commands ###
