"""empty message

Revision ID: ca9e3bf1a4e7
Revises: 9d5b6c5c31a5
Create Date: 2023-09-21 13:52:27.060722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9e3bf1a4e7'
down_revision = '9d5b6c5c31a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('relative_location', sa.String(length=255), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'relative_location', 'type', name='reference_cache_uniq')
    )
    with op.batch_alter_table('reference_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_cache_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_cache_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_cache_relative_location'), ['relative_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_cache_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_cache_type'))
        batch_op.drop_index(batch_op.f('ix_reference_cache_relative_location'))
        batch_op.drop_index(batch_op.f('ix_reference_cache_identifier'))
        batch_op.drop_index(batch_op.f('ix_reference_cache_display_name'))

    op.drop_table('reference_cache')
    # ### end Alembic commands ###
