"""empty message

Revision ID: cf591db15cec
Revises: c3abd6eefbff
Create Date: 2025-09-11 06:30:44.898304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf591db15cec'
down_revision = 'c3abd6eefbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lane_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.drop_column('lane_name')

    # ### end Alembic commands ###
