"""empty message

Revision ID: d6e5b3af0908
Revises: 9f0b1662a8af
Create Date: 2023-02-27 11:10:28.058014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e5b3af0908'
down_revision = '9f0b1662a8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_task', sa.Column('bpmn_process_identifier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human_task', 'bpmn_process_identifier')
    # ### end Alembic commands ###
