"""empty message

Revision ID: d933f94ae3bf
Revises: a6f39b4dd3b8
Create Date: 2023-11-21 12:28:47.206236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd933f94ae3bf'
down_revision = 'a6f39b4dd3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_instructions_for_end_user',
    sa.Column('task_guid', sa.String(length=36), nullable=False),
    sa.Column('instruction', sa.String(length=255), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.PrimaryKeyConstraint('task_guid')
    )
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_instructions_for_end_user_process_instance_id'), ['process_instance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_instructions_for_end_user_process_instance_id'))

    op.drop_table('task_instructions_for_end_user')
    # ### end Alembic commands ###
