"""empty message

Revision ID: d9d54e36c69f
Revises: 7f3a2c1d9b8e
Create Date: 2026-05-18 14:33:49.144747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9d54e36c69f'
down_revision = '7f3a2c1d9b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_caller_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_caller_cache_process_identifier'))

    op.drop_table('process_caller_cache')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_model_identifiers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('process_model_identifiers')

    op.create_table('process_caller_cache',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('process_identifier', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255), nullable=True),
    sa.Column('calling_process_identifier', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('process_caller_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_caller_cache_process_identifier'), ['process_identifier'], unique=False)

    # ### end Alembic commands ###
