"""empty message

Revision ID: def2cbb0ca6b
Revises: 6315ff2525b0
Create Date: 2023-03-03 09:23:19.480250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'def2cbb0ca6b'
down_revision = '6315ff2525b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('process_instance', 'bpmn_process_definition_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('process_instance', 'bpmn_process_definition_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
