"""empty message

Revision ID: e102044e51f8
Revises: 88188256d1a5
Create Date: 2025-11-21 11:06:50.076905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e102044e51f8'
down_revision = '88188256d1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pkce_code_verifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pkce_id', sa.String(length=512), nullable=False),
    sa.Column('code_verifier', sa.String(length=512), nullable=False),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pkce_id')
    )
    with op.batch_alter_table('pkce_code_verifier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pkce_code_verifier_created_at_in_seconds'), ['created_at_in_seconds'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkce_code_verifier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pkce_code_verifier_created_at_in_seconds'))

    op.drop_table('pkce_code_verifier')
    # ### end Alembic commands ###
