"""empty message

Revision ID: e2972eaf8469
Revises: 389800c352ee
Create Date: 2023-03-13 22:00:21.579493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2972eaf8469'
down_revision = '389800c352ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_instance_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=False),
    sa.Column('run_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('locked_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_instance_queue_locked_at_in_seconds'), 'process_instance_queue', ['locked_at_in_seconds'], unique=False)
    op.create_index(op.f('ix_process_instance_queue_locked_by'), 'process_instance_queue', ['locked_by'], unique=False)
    op.create_index(op.f('ix_process_instance_queue_process_instance_id'), 'process_instance_queue', ['process_instance_id'], unique=True)
    op.create_index(op.f('ix_process_instance_queue_status'), 'process_instance_queue', ['status'], unique=False)
    #op.alter_column('message_instance', 'user_id',
    #           existing_type=mysql.INTEGER(),
    #           nullable=True)
    op.drop_column('process_instance', 'locked_by')
    op.drop_column('process_instance', 'locked_at_in_seconds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_instance', sa.Column('locked_at_in_seconds', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('process_instance', sa.Column('locked_by', mysql.VARCHAR(length=80), nullable=True))
    #op.alter_column('message_instance', 'user_id',
    #           existing_type=mysql.INTEGER(),
    #           nullable=False)
    op.drop_index(op.f('ix_process_instance_queue_status'), table_name='process_instance_queue')
    op.drop_index(op.f('ix_process_instance_queue_process_instance_id'), table_name='process_instance_queue')
    op.drop_index(op.f('ix_process_instance_queue_locked_by'), table_name='process_instance_queue')
    op.drop_index(op.f('ix_process_instance_queue_locked_at_in_seconds'), table_name='process_instance_queue')
    op.drop_table('process_instance_queue')
    # ### end Alembic commands ###
