"""empty message

Revision ID: e494a3955ce5
Revises: dc8f4b664e78
Create Date: 2023-02-28 17:41:51.208350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e494a3955ce5'
down_revision = 'dc8f4b664e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spiff_step_details', 'delta_json',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spiff_step_details', 'delta_json',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###
