"""empty message

Revision ID: e8fccf29fe24
Revises: efa7a9f771a6
Create Date: 2025-11-20 12:45:21.142802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fccf29fe24'
down_revision = 'efa7a9f771a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pkce_code_verifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pkce_id', sa.String(length=512), nullable=False),
    sa.Column('code_verifier', sa.String(length=512), nullable=False),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pkce_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pkce_code_verifier')
    # ### end Alembic commands ###
