"""empty message

Revision ID: ebf5e733d109
Revises: 64adf34a98db
Create Date: 2023-08-03 11:51:07.231821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebf5e733d109'
down_revision = '64adf34a98db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.alter_column('form_file_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('ui_form_file_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task', schema=None) as batch_op:
        batch_op.alter_column('ui_form_file_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               existing_nullable=True)
        batch_op.alter_column('form_file_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
