"""empty message

Revision ID: ed304a221f59
Revises: 844cee572018
Create Date: 2023-09-11 12:24:16.923601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed304a221f59'
down_revision = '844cee572018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=36), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by_user_id', name='service_account_uniq')
    )
    with op.batch_alter_table('service_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_account_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_account_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_account_name'), ['name'], unique=False)

    with op.batch_alter_table('principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_account_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('principal_service_account_id_uniq', ['service_account_id'])
        batch_op.create_foreign_key("principal_service_account_fk", 'service_account', ['service_account_id'], ['id'])

        # manually added
        batch_op.drop_constraint('principal_chk_1', type_='check')
        batch_op.create_check_constraint('principal_chk_2', 'NOT(user_id IS NULL AND group_id IS NULL AND service_account_id IS NULL)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('principal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('service_account_id')
        batch_op.drop_constraint('principal_chk_1', type_="check")
        batch_op.create_check_constraint('principal_chk_1', 'NOT(user_id IS NULL AND group_id IS NULL)')

    with op.batch_alter_table('service_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_account_name'))
        batch_op.drop_index(batch_op.f('ix_service_account_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_account_api_key'))

    op.drop_table('service_account')
    # ### end Alembic commands ###
