"""empty message

Revision ID: ef3fc0930156
Revises: 5d07e3db3ab7
Create Date: 2023-11-22 15:44:39.017987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3fc0930156'
down_revision = '5d07e3db3ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_been_retrieved', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_task_instructions_for_end_user_has_been_retrieved'), ['has_been_retrieved'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_instructions_for_end_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_instructions_for_end_user_has_been_retrieved'))
        batch_op.drop_column('has_been_retrieved')

    # ### end Alembic commands ###
