"""empty message

Revision ID: efa7a9f771a6
Revises: 0ee3c2c7faf7
Create Date: 2025-10-08 17:08:46.538115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa7a9f771a6'
down_revision = '0ee3c2c7faf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_triggerable_process_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_triggerable_process_model_message_name'))
        batch_op.create_index(batch_op.f('ix_message_triggerable_process_model_message_name'), ['message_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_triggerable_process_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_triggerable_process_model_message_name'))
        batch_op.create_index(batch_op.f('ix_message_triggerable_process_model_message_name'), ['message_name'], unique=False)

    # ### end Alembic commands ###
