"""empty message

Revision ID: f04cbd9f43ec
Revises: 1073364bc015
Create Date: 2023-08-23 11:05:04.368165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04cbd9f43ec'
down_revision = '1073364bc015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_milestone_bpmn_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_instance', schema=None) as batch_op:
        batch_op.drop_column('last_milestone_bpmn_name')

    # ### end Alembic commands ###
