"""empty message

Revision ID: fdf522e4c48a
Revises: ac6b60d7fee9
Create Date: 2023-02-28 14:50:26.030983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf522e4c48a'
down_revision = 'ac6b60d7fee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serialized_bpmn_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('static_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serialized_bpmn_definition')
    # ### end Alembic commands ###
