services:
  spiffworkflow-frontend:
    build:
      context: spiffworkflow-frontend
      dockerfile: dev.Dockerfile
    user: "${RUN_AS}"
    environment:
      HOST: "0.0.0.0"
      PORT: "${SPIFFWORKFLOW_FRONTEND_PORT:-8001}"
      XDG_CACHE_HOME: "/app/.cache"
    volumes:
      - ./spiffworkflow-frontend:/app
