services:
  spiffworkflow-frontend:
    build:
      context: spiffworkflow-frontend
      dockerfile: dev.Dockerfile
    user: "${RUN_AS}"
    environment:
      #CYPRESS_CACHE_FOLDER: "/app/.cache/cypress"
      HOST: "0.0.0.0"
      PORT: "${SPIFFWORKFLOW_FRONTEND_PORT:-8001}"
      #npm_config_cache: "/app/.cache/npm"
      XDG_CACHE_HOME: "/app/.cache"
    volumes:
      - ./spiffworkflow-frontend:/app
