import time
import re
from playwright.sync_api import expect, BrowserContext, Page

from helpers.login import login
from helpers.playwright_setup import browser_context  # Import the fixture


def test_process_model_import(browser_context: BrowserContext):
    """Test importing a process model from GitHub."""
    page = browser_context.new_page()
    
    # Login as admin
    login(page, "admin", "admin")
    
    # Navigate to a process group
    page.goto("http://localhost:7001/process-groups")
    # Wait for page to load
    expect(page).to_have_title("SpiffWorkflow")
    
    # Create a test process group if it doesn't exist
    test_group_name = "Import Test Group"
    
    # Check if our test group exists
    test_group = page.get_by_text(test_group_name)
    if not test_group.is_visible():
        # Create a new process group
        # Get the button within the Process Groups section
        page.locator("text='Process Groups'").locator("xpath=./following::button").first.click()
        page.get_by_label("Display name").fill(test_group_name)
        page.get_by_label("ID").fill("import-test-group")
        page.get_by_test_id("add-process-group-save-button").click()
        
        # Verify the group was created
        expect(page.get_by_text(test_group_name)).to_be_visible()
    
    # Click on the process group
    page.get_by_text(test_group_name).click()
    
    # Verify we're on the process models page
    expect(page).to_have_url(re.compile(r"/process-groups/import-test-group/process-models$"))
    expect(page.get_by_test_id("create-process-model-button")).to_be_visible()
    
    # Look for the import button
    import_button = page.get_by_test_id("process-model-import-button")
    expect(import_button).to_be_visible()
    
    # Click the import button
    import_button.click()
    
    # Wait for the import dialog to appear
    dialog = page.get_by_text("Import Process Model from GitHub")
    expect(dialog).to_be_visible()
    
    # Enter the GitHub URL
    url_input = page.get_by_test_id("repository-url-input")
    expect(url_input).to_be_visible()
    url_input.fill("https://github.com/sartography/example-process-models/tree/main/examples/0-1-minimal-example")
    
    # Click the import button
    import_button = page.get_by_test_id("import-button")
    expect(import_button).to_be_enabled()
    import_button.click()
    
    # Wait for the import to complete and redirect to the process model page
    # ID will be automatically generated by the backend
    # The imported model will likely have a name based on the directory name in the URL
    page.wait_for_url(re.compile(r"process-models/import-test-group/.+"))
    
    # Verify we're on a process model page
    expect(page).to_have_url(re.compile(r"process-models/import-test-group/.+"))
    
    # Verify the imported files
    # Look for BPMN diagram or process model details
    expect(page.get_by_text("Process Model Details")).to_be_visible()
    
    # Navigate to files tab to verify files were imported
    page.get_by_test_id("process-model-files-tab").click()
    
    # Check if process_model.json exists
    expect(page.get_by_text("process_model.json")).to_be_visible()
    
    # Check if a BPMN file exists
    expect(page.locator("text=.bpmn")).to_be_visible()
    
    # Clean up the imported process model
    # Go back to process models list
    page.goto(f"http://localhost:7001/process-groups/import-test-group/process-models")
    
    # Verify we're back at the process models list
    expect(page).to_have_url(re.compile(r"/process-groups/import-test-group/process-models$"))


if __name__ == "__main__":
    # For manual testing
    import sys
    from playwright.sync_api import sync_playwright
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False, slow_mo=100)
        context = browser.new_context()
        test_process_model_import(context)
        browser.close()