users:
  testadmin1:
    service: https://testing/openid/thing
    email: testadmin1@spiffworkflow.org
    password: admin
    preferred_username: El administrador de la muerte

groups:
  admin:
    users: [testadmin1, testadmin2]

  Finance Team:
    users: [testuser1, testuser2]

  hr:
    users: [testuser2, testuser3, testuser4]

permissions:
  process-groups-all:
    groups: [admin]
    allowed_permissions: [all]
    uri: PG:ALL
  basic:
    groups: [admin]
    allowed_permissions: [all]
    uri: BASIC
  elevated-operations:
    groups: [admin]
    allowed_permissions: [all]
    uri: ELEVATED

  basic-permission:
    groups: [everybody]
    allowed_permissions: [all]
    uri: BASIC

  finance-admin-group:
    groups: ["Finance Team"]
    allowed_permissions: [all]
    uri: PG:finance

  finance-hr-start:
    groups: ["hr"]
    allowed_permissions: [start]
    uri: PG:finance

  read-all-finance:
    groups: [hr]
    allowed_permissions: [read]
    uri: PG:finance
