users:
  testadmin1:
    service: https://testing/openid/thing
    email: testadmin1@spiffworkflow.org
    password: admin
    preferred_username: El administrador de la muerte

groups:
  admin:
    users: [testadmin1, testadmin2]

  Finance Team:
    users: [testuser1, testuser2]

  hr:
    users: [testuser2, testuser3, testuser4]

permissions:
  admin:
    groups: [admin]
    allowed_permissions: [create, read, update, delete]
    uri: /*

  read-all:
    groups: ["Finance Team", hr, admin]
    allowed_permissions: [read]
    uri: /*

  process-instances-find-by-id:
    groups: [everybody]
    allowed_permissions: [read]
    uri: /process-instances/find-by-id/*

  tasks-crud:
    groups: [everybody]
    allowed_permissions: [create, read, update, delete]
    uri: /tasks/*

  finance-admin-group:
    groups: ["Finance Team"]
    allowed_permissions: [all]
    uri: PG:finance

  finance-hr-start:
    groups: ["hr"]
    allowed_permissions: [start]
    uri: PG:finance

  finance-admin-model-lanes:
    groups: ["Finance Team"]
    allowed_permissions: [create, read, update, delete]
    uri: /process-models/finance:model_with_lanes/*

  finance-admin-instance-run:
    groups: ["Finance Team"]
    allowed_permissions: [create, read, update, delete]
    uri: /process-instances/*
