"""Staging."""
from os import environ

SPIFFWORKFLOW_BACKEND_GIT_BRANCH = environ.get(
    "SPIFFWORKFLOW_BACKEND_GIT_BRANCH", default="staging"
)
SPIFFWORKFLOW_BACKEND_GIT_PUBLISH_TARGET_BRANCH = environ.get(
    "SPIFFWORKFLOW_BACKEND_GIT_PUBLISH_TARGET_BRANCH", default="main"
)
SPIFFWORKFLOW_BACKEND_GIT_COMMIT_ON_SAVE = False
SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME = "staging.yml"
